print.greedy <- function(x, ...) {

  # general
  cat("Object of class 'nem.greedy' generated by 'nem.greedy()'\n")
  cat("\n")
  
  # slots
  cat("$graph:  phenotypic hierarchy on",ncol(x$graph),"genes)\n")  
  cat("\n")
     
  #
  #cat("\n")
  #cat("plot this object to see the graph\n")

}
  
