print.pairwise <- function(x, ...) {

  # general
  cat("Object of class 'pairwise' generated by 'pairwise.posterior()'\n")
  cat("\n")
  
  # slots
  cat("$graph:  phenotypic hierarchy on",ncol(x$graph),"genes)\n")
  cat("$scores: posterior distributions of local models\n")
  cat("\n")
  
  # summary
  cat("Summary of MAP estimates:\n") 
  tmp         <- table(apply(x$scores[,1:4],1,which.max))
  summ        <- c(sum(tmp),tmp[1],tmp[2]+tmp[3],tmp[4])
  names(summ) <- c("all","..","->","<->")
  print(summ)
  
  #
  #cat("\n")
  #cat("plot this object to see the graph\n")

}
  
