print.ModuleNetwork <- function(x, ...) {

  # general
  cat("Object of class 'ModuleNetwork' generated by 'moduleNetwork()'\n")
  cat("\n")
  
  # slots
  cat("$graph:  phenotypic hierarchy on",ncol(x$graph),"genes)\n")  
  cat("\n")
     
  #
  #cat("\n")
  #cat("plot this object to see the graph\n")

}
  
