print.triples <- function(x, ...) {

  # general
  cat("Object of class 'triples' generated by 'triples.posterior()'\n")
  cat("\n")
  
  # slots
  cat("$graph:  phenotypic hierarchy on",ncol(x$graph),"genes\n")
  cat("$avg:    matrix of edge frequencies in triple models")
  
  #cat("\n")  
  #cat("plot this object to see the graph\n")

}
  
